name: Release
on:
  release:
    types: [created]

jobs:
  release:
    needs: source-archive
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: "aix"
            arch: "ppc64"
          - os: "android"
            arch: "386"
          - os: "android"
            arch: "amd64"
          - os: "android"
            arch: "arm"
          - os: "android"
            arch: "arm64"
          - os: "darwin"
            arch: "amd64"
          - os: "darwin"
            arch: "arm64"
          - os: "dragonfly"
            arch: "amd64"
          - os: "freebsd"
            arch: "386"
          - os: "freebsd"
            arch: "amd64"
          - os: "freebsd"
            arch: "arm"
          - os: "freebsd"
            arch: "arm64"
          - os: "illumos"
            arch: "amd64"
          - os: "ios"
            arch: "amd64"
          - os: "ios"
            arch: "arm64"
          - os: "js"
            arch: "wasm"
          - os: "linux"
            arch: "386"
          - os: "linux"
            arch: "amd64"
          - os: "linux"
            arch: "arm"
          - os: "linux"
            arch: "arm64"
          - os: "linux"
            arch: "mips"
          - os: "linux"
            arch: "mips64"
          - os: "linux"
            arch: "mips64le"
          - os: "linux"
            arch: "mipsle"
          - os: "linux"
            arch: "ppc64"
          - os: "linux"
            arch: "ppc64le"
          - os: "linux"
            arch: "riscv64"
          - os: "linux"
            arch: "s390x"
          - os: "netbsd"
            arch: "386"
          - os: "netbsd"
            arch: "amd64"
          - os: "netbsd"
            arch: "arm"
          - os: "netbsd"
            arch: "arm64"
          - os: "openbsd"
            arch: "386"
          - os: "openbsd"
            arch: "amd64"
          - os: "openbsd"
            arch: "arm"
          - os: "openbsd"
            arch: "arm64"
          - os: "plan9"
            arch: "386"
          - os: "plan9"
            arch: "amd64"
          - os: "plan9"
            arch: "arm"
          - os: "solaris"
            arch: "amd64"
          - os: "wasip1"
            arch: "wasm"
          - os: "windows"
            arch: "386"
          - os: "windows"
            arch: "amd64"
          - os: "windows"
            arch: "arm"
          - os: "windows"
            arch: "arm64"
    steps:
      - name: Setup bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: ${{ runner.os }}-${{ matrix.arch }}-bazel-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch }}-bazel-
      - name: "Test"
        run: "bazel test --test_output=errors //..."
      - name: "Build binaries for ${{ matrix.os }}_${{ matrix.arch }}"
        run: "bazel build --platforms=@io_bazel_rules_go//go/toolchain:${{ matrix.os }}_${{ matrix.arch}} --//cmd/gotopt2:name_part_from_command_line=${{ matrix.os }}-${{ matrix.arch }} //cmd/gotopt2:zip //cmd/gotopt2-generator:zip"
      - name: "Publish ${{ matrix.os }}_${{ matrix.arch }}"
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          artifacts: "bazel-bin/cmd/gotopt2/gotopt2-${{ matrix.os }}-${{ matrix.arch }}.zip,bazel-bin/cmd/gotopt2-generator/gotopt2-generator-${{ matrix.os }}-${{ matrix.arch }}.zip"
  source-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get release tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Get repo name
        id: get_repo_name
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: "${{ env.REPO_NAME }}-${{ env.VERSION }}.zip"
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: "Publish source archive"
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          artifacts: "${{ env.REPO_NAME }}-${{ env.VERSION }}.zip"

