name: Release
on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["amd64"]
        os: ["linux", "darwin"]
    steps:
      - name: Setup bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 6.0.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: "bazel test //..."
      - name: "Build binaries"
        run: "bazel build --platforms=@io_bazel_rules_go//go/toolchain:${{ matrix.os }}_${{ matrix.arch}} //cmd/..."
      - name: Publish ${{ matrix.os }} ${{ matrix. arch }}
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'bazel-bin/cmd/gotopt2/gotopt_/gotopt2'

