# When run:
# * runs tests to ensure that released version works.
# * tags a new release based on main top of tree.
# * builds a source bundle and uploads it into the release
# * builds binaries and uploads them into the release
#
# The workflow can be run manually, otherwise it runs once a week.
name: Tag and Release

env:
  # The env here is tailored to releasing *one* binary.
  # ZIP_PACKAGE is the package where the zip target is. For //test in this
  # example, the label of the bazel target that zips up a built and released
  # binary is `//test:zip`.
  ZIP_PACKAGE: "//cmd/gotopt2"
  # The name of the binary to package. This workflow packages a single binary
  # into a zip file.
  BINARY_NAME: "bazel-bin/cmd/gotopt2/gotopt2"

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Setup bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Test"
        run: "bazel test --test_output=errors //..."
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          generateReleaseNotes: true
      - name: Get release tag
        id: get_version
        run: echo "VERSION=${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_ENV
      - name: Get repo name
        id: get_repo_name
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      - name: "Publish source archive"
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: "${{ env.REPO_NAME }}-${{ env.VERSION }}.zip"
          exclusions: '*.git* /*node_modules/* .editorconfig /bazel-*'
      - name: "Upload source archive"
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          allowUpdates: true
          artifacts: "${{ env.REPO_NAME }}-${{ env.VERSION }}.zip"

  release:
    needs: tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: "aix"
            arch: "ppc64"
          - os: "android"
            arch: "386"
          - os: "android"
            arch: "amd64"
          - os: "android"
            arch: "arm"
          - os: "android"
            arch: "arm64"
          - os: "darwin"
            arch: "amd64"
          - os: "darwin"
            arch: "arm64"
          - os: "dragonfly"
            arch: "amd64"
          - os: "freebsd"
            arch: "386"
          - os: "freebsd"
            arch: "amd64"
          - os: "freebsd"
            arch: "arm"
          - os: "freebsd"
            arch: "arm64"
          - os: "illumos"
            arch: "amd64"
          - os: "ios"
            arch: "amd64"
          - os: "ios"
            arch: "arm64"
          - os: "js"
            arch: "wasm"
          - os: "linux"
            arch: "386"
          - os: "linux"
            arch: "amd64"
          - os: "linux"
            arch: "arm"
          - os: "linux"
            arch: "arm64"
          - os: "linux"
            arch: "mips"
          - os: "linux"
            arch: "mips64"
          - os: "linux"
            arch: "mips64le"
          - os: "linux"
            arch: "mipsle"
          - os: "linux"
            arch: "ppc64"
          - os: "linux"
            arch: "ppc64le"
          - os: "linux"
            arch: "riscv64"
          - os: "linux"
            arch: "s390x"
          - os: "netbsd"
            arch: "386"
          - os: "netbsd"
            arch: "amd64"
          - os: "netbsd"
            arch: "arm"
          - os: "netbsd"
            arch: "arm64"
          - os: "openbsd"
            arch: "386"
          - os: "openbsd"
            arch: "amd64"
          - os: "openbsd"
            arch: "arm"
          - os: "openbsd"
            arch: "arm64"
          - os: "plan9"
            arch: "386"
          - os: "plan9"
            arch: "amd64"
          - os: "plan9"
            arch: "arm"
          - os: "solaris"
            arch: "amd64"
          - os: "wasip1"
            arch: "wasm"
          - os: "windows"
            arch: "386"
          - os: "windows"
            arch: "amd64"
          - os: "windows"
            arch: "arm"
          - os: "windows"
            arch: "arm64"
    steps:
      - name: Setup bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Test"
        run: "bazel test --test_output=errors //..."
      - name: "Build binaries for ${{ matrix.os }}_${{ matrix.arch }}"
        run: |
          bazel build \
            --platforms=@rules_go//go/toolchain:${{ matrix.os }}_${{ matrix.arch}} \
            --${ZIP_PACKAGE}:name_part_from_command_line=${{ matrix.os }}-${{ matrix.arch }} \
            ${ZIP_PACKAGE}:zip
      - name: Find version tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          dry_run: true
      - name: "Publish ${{ matrix.os }}_${{ matrix.arch }}"
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          artifacts: "${{ env.BINARY_NAME }}-${{ matrix.os }}-${{ matrix.arch }}.zip"
          tag: ${{ steps.tag_version.outputs.previous_tag }}

